# ~/.config/starship.toml

format = """
[](fg:blue)\
$directory\
[](fg:blue bg:purple)\
$git_branch\
$git_status\
[](fg:purple bg:green)\
$nodejs\
$python\
$rust\
[](fg:green)\
$line_break\
$character
"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
format = "[ $path ]($style)"
style = "bg:blue fg:black"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "
style = "bg:purple fg:black"

[git_status]
format = "[$all_status$ahead_behind ]($style)"
style = "bg:purple fg:black"

[nodejs]
format = "[ $symbol($version) ]($style)"
symbol = " "
style = "bg:green fg:black"

[python]
format = "[ $symbol($version) ]($style)"
symbol = " "
style = "bg:green fg:black"

[rust]
format = "[ $symbol($version) ]($style)"
symbol = " "
style = "bg:green fg:black"
